version: '3.8'

services:
    dissertation_db:
      build: 
          context: .
          dockerfile: DockerfileSql
      restart: always
      ports:  
          - "7000:1433"
      env_file:
          - sqlserver.env
          - .env.database
      volumes: 
          - sqlsystem:/var/opt/mssql/
          - sqldata:/var/opt/sqlserver/data
          - sqllog:/var/opt/sqlserver/log
          - sqlbackup:/var/opt/sqlserver/backup
      networks:
        - dissertation_app_network

    dissertation_api: 
      build:
        context: .
        dockerfile: Dissertation_API/Dockerfile
      restart: on-failure
      ports: 
        - "8000:8000"
        - "8001:8001"
      depends_on:
        - dissertation_db
      networks:
        - dissertation_app_network
      env_file:
        - .env.dissertation
      volumes:
        - ~/.aspnet/https:/https

    notification_api: 
      build:
        context: .
        dockerfile: Notification_API/Dockerfile
      restart: on-failure
      ports: 
        - "9000:9000"
        - "9001:9001"
      depends_on:
        - dissertation_db
      networks:
        - dissertation_app_network
      env_file:
        - .env.notification
      volumes:
        - ~/.aspnet/https:/https

volumes:
  sqlsystem:
  sqldata:
  sqllog:
  sqlbackup:

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  dissertation_app_network:
    external: true

