version: '3.8'

services:
    dissertation_db:
      build: 
          context: .
          dockerfile: DockerfileSql
      restart: always
      ports:  
          - "1433:1433"
      env_file:
          - sqlserver.env
          - .env.database
      volumes: 
          - sqlsystem:/var/opt/mssql/
          - sqldata:/var/opt/sqlserver/data
          - sqllog:/var/opt/sqlserver/log
          - sqlbackup:/var/opt/sqlserver/backup
      networks:
        - dissertation_app_network

    api_gateway: 
      build:
        context: .
        dockerfile: Gateway_Solution/Dockerfile
      restart: on-failure
      ports: 
        - "5000:5000"
        - "5001:5001"
      depends_on:
        - dissertation_db
        - user_management_api
        - dissertation_api
        - notification_api
      networks:
        - dissertation_app_network
      env_file:
        - Gateway_Solution/.env.gateway
      volumes:
        - ~/.aspnet/https:/https
          
    user_management_api:
      build:
        context: .
        dockerfile: UserManagement_API/Dockerfile
      restart: on-failure
      ports:
        - "7000:7000"
        - "7001:7001"
      depends_on:
        - dissertation_db
      networks:
        - dissertation_app_network
      env_file:
        - UserManagement_API/.env.user
      volumes:
        - ~/.aspnet/https:/https

    dissertation_api: 
      build:
        context: .
        dockerfile: Dissertation.Api/Dockerfile
      restart: on-failure
      ports: 
        - "8000:8000"
        - "8001:8001"
      depends_on:
        - dissertation_db
      networks:
        - dissertation_app_network
      env_file:
        - Dissertation.Api/.env.dissertation
      volumes:
        - ~/.aspnet/https:/https

    notification_api: 
      build:
        context: .
        dockerfile: Notification_API/Dockerfile
      restart: on-failure
      ports: 
        - "9000:9000"
        - "9001:9001"
      depends_on:
        - dissertation_db
      networks:
        - dissertation_app_network
      env_file:
        - Notification_API/.env.notification
      volumes:
        - ~/.aspnet/https:/https
    
    portainer:
      image: portainer/portainer-ce
      container_name: portainer
      restart: always
      ports:
        - "8080:8000"
        - "9090:9000"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data

volumes:
  sqlsystem:
  sqldata:
  sqllog:
  sqlbackup:
  portainer_data:
  elasticsearch-data:

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  dissertation_app_network:
    external: true

